### ISSUE TITLE
Kanban board setup for RoR group project

### ISSUE THREAD

**Issue by jaferIdrees** [jaferIdrees/recipe_app#14]
We are a group of 3 teammates 
@Fourteen98 
@Gedewon 
@jaferIdrees 
Link to the project ( https://github.com/users/jaferIdrees/projects/4/views/1)

**Comment by omar-muhamad** [comment]
# Invalid ❌

Hi Team,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] The project link that you provided is broken, Please fix that.

![image](https://user-images.githubusercontent.com/68796232/200384280-4ddad5d3-554a-4493-8540-ed875788868f.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by Ismailco** [comment]
### Hi @jaferIdrees, @Gedewon, @Fourteen98, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ Issue has required information
✔️ Set up the Kanban board

## Required Changes ♻️
- [ ] The kanban board should include all the columns, kindly consider adding the `In Review` column to your board
- [ ] [OPTIONAL] The `pt` is not divided equally between all the students, kindly check the number of tasks in every student should be equally divided
- [ ] Some of the issue has no description, kindly insure all the tasks have a description

| | |
|-|-|
|![Screenshot_20221107_204709](https://user-images.githubusercontent.com/25227022/200401069-c64ee31c-b939-4104-bc77-bbc5a3279dc0.png)|![Screenshot_20221107_204726](https://user-images.githubusercontent.com/25227022/200401094-8a23a8db-a9fc-4d67-ad6f-c66e3e0dadf9.png)|

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Image](https://c.tenor.com/CWrSBML0hC8AAAAC/little-dinosaur-so-close.gif)

 ## Required Changes ♻️
- [ ] As suggested by the previous reviewer, kindly make sure that all of the tasks have a proper description. Currently, the following task has no description:
   - #2 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MahmoudBakr23** [comment]
Hi team 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Great work with the requested changes from the previous reviewers

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
